# Generated by Django 5.2.1 on 2025-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AI Image Detector', max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/')),
                ('title', models.CharField(default='AI Image Detector', max_length=128)),
                ('probability', models.FloatField(default=0)),
                ('result', models.CharField(choices=[('R', 'Real'), ('F', 'Fake'), ('N', 'Chưa Xác Định')], default='N', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
